video_path: /mnt/nas4/taeyeon/datasets/davis/480p/tennis_short
save_dir: /mnt/nas4/taeyeon/datasets/davis/480p/tennis_short/still/ddim_latent
max_number_of_frames: 24

n_timesteps: 999
prompt: Amazing quality, masterpiece, A man playing tennis
negative_prompt: ""
save_ddim_reconstruction: False
